SOURCES = vm.cpp

MAIN_SOURCE = main.cpp

LIBRARY_EXTRAS = ../compiler/compile.o \
				../parser/parse.o \
				../lexser/lex.o
LIBRARY_OUT = vmlib.o
INTERGRATE_TEST_OUT = vmprog.out

all: $(LIBRARY_OUT)
include ../Makefile.common
