SOURCES = ir_compiler.cpp \
		  asm_compiler.cpp\
		  lex_split.cpp\
		  assembler.cpp

MAIN_SOURCE = main.cpp

LIBRARY_EXTRAS = ../parser/parse.o \
				 ../lexser/lex.o
LIBRARY_OUT = compile.o
INTERGRATE_TEST_OUT = compilerprog.out

all: $(LIBRARY_OUT)
include ../Makefile.common