SOURCES = interpreter.cpp

MAIN_SOURCE = main.cpp

LIBRARY_EXTRAS = ../parser/parse.o \
				../lexser/lex.o
LIBRARY_OUT = interprete.o
INTERGRATE_TEST_OUT = interpreterprog.out

all: $(LIBRARY_OUT)
include ../Makefile.common