SOURCES = lexser.cpp \
		reserved_list.cpp

TEST_SOURCES = lexser_test.cpp

MAIN_SOURCE = main.cpp

LIBRARY_OUT = lex.o
UNIT_TEST_OUT = lexunit.out
INTERGRATE_TEST_OUT = lexprog.out

all: $(LIBRARY_OUT)
include ../Makefile.common